### ISSUE TITLE
New Feature: Now Playing 

### ISSUE THREAD

**Issue by subhangiP** [oguzhnatly/flutter_carplay#33]
Hello,

when can we expect New Feature: Now Playing update?
is there any ETA for the same?

Thankyou!!!

**Comment by maendamedia** [comment]
I like to know also. Would be a great addition

**Comment by bensalcie** [comment]
You can try from this Branch.
Add this to your pub spec.yaml

```
flutter_carplay: 
    git:
      url: https://github.com/bensalcie/flutter_carplay.git # Where to find Repo
      ref: Carplay-support-image-from-url # branch name
```

Call the now Now Playing Template in flutter:
(Assuming you already sent your media item to the media queue)

`    await FlutterCarplay.showSharedNowPlaying(animated: true);
`
